### ISSUE TITLE
Bug with entering multiple operators one after the other 

### ISSUE THREAD

**Issue by Devansh-Baghel** [1paramveer/Calculator#1]
Currently user can click an operator right after clicking another operator and that produces this in the display:

![image](https://github.com/1paramveer/Calculator/assets/77718741/51cbf5f0-02b9-41b8-98b5-08fb8f9160da)

A quick fix could be to check the last index of whatever the user enters and if it's an operator then not allowing user to click.

**Comment by 1paramveer** [comment]
Thanks! , fixed it (●'◡'●)
